name = "check_positive"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Dan Duguay"]
maintainers = ["Dan Duguay <Duguay9@gmail.com>"]
maintainers-logins = ["DanDuguay"]

executables = ["check_positive"]
